### ISSUE TITLE
Failed at the snake-skin-vue@1.0.0 build script.

### ISSUE THREAD

**Issue by Schillers** [countercept/snake#1]
Hi,

Been trying to install this on a VPS Hosting Ubuntu 16.04 but keep getting this error. Have you encountered this before?

> snake-skin-vue@1.0.0 build /root/snake/snake-skin
> node build/build.js
sudo
⠧ building for production...Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! snake-skin-vue@1.0.0 build: `node build/build.js`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the snake-skin-vue@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-16T19_04_43_447Z-debug.log
mv: cannot stat 'dist': No such file or directory

Thanks in advance!

**Comment by Schillers** [comment]
Little more digging around on this. Looks as though during the set up, the system ran out of memory and crashed the setup.

I migrated to a system with 768MB and installed.

**Comment by alexkornitzer** [comment]
Ah awesome, was just about to say are you on the latest npm but seems like you have solved it. Don’t hesitate to raise any other issues you encounter :)

Alex
