### ISSUE TITLE
Need help with installing snake! 

### ISSUE THREAD

**Issue by bedangSen** [countercept/snake#12]
![image](https://user-images.githubusercontent.com/35425072/65321010-2d2c8780-dbb4-11e9-9a8c-8ebf9db54f1c.png)

Hey guys! 

I am having a little difficulty installing snake. Can someone help me out? ^^

**Comment by alexkornitzer** [comment]
Hey, so i assume you have done a system based install over a user based install if you are using the systemd services? I have just finished porting the new ui so I will be improving and updating the install process soon, as the current one is a tad temperamental. (Still need to document the docker version). 

Are you able to provide a few more details than the above, i.e. the install process you followed?

Alex

**Comment by zetahoq** [comment]
I am getting the same error.  Using a fresh install of Ubuntu 16.04.6 and following the directions for installation provided in the README.

**Comment by alexkornitzer** [comment]
Will try and replicate using the distro above

**Comment by alexkornitzer** [comment]
Was due to errors in the install script, closing out.
