### ISSUE TITLE
Upload Failed...

### ISSUE THREAD

**Issue by alecisec** [countercept/snake#17]
I'm just using the docker-compose script with only one change, the skin port changed to 80 from 8080 and I'm not able to upload any files.

logs from snake docker container as follows:

snake_1       | [W 200604 06:41:45 snake_handler:208] upload/file - no 'file' in part
snake_1       | [W 200604 06:41:45 web:2106] 422 POST /upload/file (172.19.0.5) 2.38ms

**Comment by alexkornitzer** [comment]
Hmm, interesting, will check this out when also testing the setup.sh. The above implies that the front end is not creating the request to the backend correctly.

**Comment by alexkornitzer** [comment]
I swapped the port from 8080 to 80 and experienced no error, going to close this for now. There must be something that caused it so happy to try again if repeatable.

**Comment by nosferatu87** [comment]
I'm getting this issue as well. If I change the externally available port for either the API or the snake-skin in docker-compose.yml uploading files breaks.

**Comment by alexkornitzer** [comment]
Can you paste a sample of the part of the compose file you are changing then I should be able to replicate.

**Comment by nosferatu87** [comment]
I just change the external side of the port definition. If I set it to 3000:3000 then it works fine.

snake-skin:
  build:
    context: ./snake-skin
    dockerfile: Dockerfile
  environment:
    - SNAKE_SKIN_SNAKE_API=http://snake:5000
  depends_on:
    - snake
  ports:
    - "80:3000"
  links:
    - snake

**Comment by alexkornitzer** [comment]
Okay, I tried changing the above again on a clean install on Ubuntu, and I am just not getting that error. Have you got other errors in you compose log, such as snake failing to start?

**Comment by nosferatu87** [comment]
I found the error. I was also trying to redirect the environment as - SNAKE_SKIN_SNAKE_API=http://snake:443 with the snake ports setup as 443:5000. Since docker does an internal route for that you have to leave the environment as SNAKE_SKIN_SNAKE_API=http://snake:5000.

Sorry for the hassle.

**Comment by alexkornitzer** [comment]
Absolutely no worries, Snake's docker setup is slightly confusing. Will try and address it if I ever find time to start on version 2 :)
