### ISSUE TITLE
Install instructions need updating

### ISSUE THREAD

**Issue by alecisec** [countercept/snake#18]
Have tried all mentioned methods on new/clean installs of Ubuntu 16.04 , 18.04 , 20.04 and errors occur at various steps. These are all on new AWS EC2 instances and can be tested quickly.

Part of the issue seems to be the services not being created correctly in the setup sh

**Comment by alexkornitzer** [comment]
Thanks for the heads up, I will re-test the scripts on a clean machine and assess.

**Comment by alexkornitzer** [comment]
Sorry about that, the script has now been updated along with the README.
