### ISSUE TITLE
Issues with Web UI

### ISSUE THREAD

**Issue by iaeubanks** [countercept/snake#20]
Hello

I think that I have made some errors when it came to the installation of Snake on my Ubuntu 20.04 Desktop Machine. I have followed all of the instructions provided for the installation and startup of snake, snake-pit, and snake-skin. However, when I try to access the webui page, I get the following message:
![image](https://user-images.githubusercontent.com/61153798/126494738-b7128c11-3bc8-45e7-90da-997fcd6324ae.png)

I have also checked the :6379 page and get this message:
![image](https://user-images.githubusercontent.com/61153798/126494826-682eab65-b00f-4157-a8ff-4b3a40f1dffb.png)

If I could get some help regarding on how to start to fix these problems this would be greatly appreciated.

**Comment by alexkornitzer** [comment]
Hi,

Which type of install did you do? The `:6379` just means that redis is running.

If you followed the `Production` steps then you should be able to check the state of the following services:
```
systemctl status snake-pit
systemctl status snake
systemctl status snake-skin
```

If the above are running then you should be able to hit the UI on `http://127.0.0.1:8000` and the API on `http://127.0.0.1:5000`

As the instructions on the `README` are for Ubuntu `17.10` it might be that the install never successfully finished. If that is the case I will test with the latest Ubuntu LTS and update the `README`.

**Comment by iaeubanks** [comment]
The ubuntu version is most likely the problem, I was using 20.04. I will try again and use 17.10 this time to see if that makes it run smoothly.  I will test my setup and then try again using 17.10

**Comment by iaeubanks** [comment]
I tested all of the statuses and each of the services are reading active and running. The only thing is that the snake.pid appears to be referencing a path below legacy and is recommending an update. The UI is still not able to connect and the API gives this message.
![image](https://user-images.githubusercontent.com/61153798/126773833-c1e61691-69af-455a-9510-ff6bb3d3d5c6.png)

Any further recommendations on my 20.04 machine or do you recommend that I use a 17.10 machine

**Comment by alexkornitzer** [comment]
Yep so that above means the API is up and running. What error are you getting for the UI? It should all work on 20.04, i'll check it out this evening just to make sure nothing is playing up on a clean install.

**Comment by iaeubanks** [comment]
![image](https://user-images.githubusercontent.com/61153798/126776982-d6c46b3a-07ce-43a5-bc2a-edc24198fcc7.png)

This is what I see whenever I try to connect to the 8000 host.

**Comment by iaeubanks** [comment]
I also checked my hosts to see if there is a different address for my machine, and this is what I have. 
![image](https://user-images.githubusercontent.com/61153798/126777664-977ee72f-14aa-4807-88d4-557fd7f0ce05.png)

**Comment by alexkornitzer** [comment]
Right, so the above means that the UI is not running, what output are you getting for `systemctl status snake-skin`?

**Comment by iaeubanks** [comment]
![image](https://user-images.githubusercontent.com/61153798/126779811-08813924-d3ed-48ff-a627-b9d83157eb54.png)
![image](https://user-images.githubusercontent.com/61153798/126779841-086a6a8f-1979-43c3-a3f7-9bc0c790c926.png)
 This is what I see when I run the command.

**Comment by alexkornitzer** [comment]
I have a feeling I have been an idiot, can you hit it on `http://localhost:3000`?

**Comment by iaeubanks** [comment]
Yes I can. Thank you very much

**Comment by iaeubanks** [comment]
I am guessing there was a typo or just something not documented?

**Comment by alexkornitzer** [comment]
Yeah that is a typo, i'll get it fixed.

**Comment by iaeubanks** [comment]
Of course, thank you so much for your help!
