### ISSUE TITLE
What are your Contribution Guidelines?

### ISSUE THREAD

**Issue by Schillers** [countercept/snake#3]
All,

Are you able to define contribution guidelines. I am keen to contribute to the project but would like to know if there are any contribution guidelines?

Cheers!

**Comment by alexkornitzer** [comment]
Awesome,

No but there should be, let me draw some up now :D

**Comment by alexkornitzer** [comment]
Made a basic contribution guide, will probably improve it over time: [CONTRIBUTING.md](https://github.com/countercept/snake/blob/master/CONTRIBUTING.md)
