### ISSUE TITLE
errored in pydeep due to a lack of gcc

### ISSUE THREAD

**Issue by ethicalredteam** [countercept/snake#6]
i was trying to get this working on Ubuntu 16.04 vps
web gui installed successfully but upload functions did not work

install script i quickly put together
https://pastebin.com/7hDeTB9g

errors from the install
https://pastebin.com/iEPaN7GK

issue per talking with dev Alex

"Looks like it errored in pydeep due to a lack of gcc, which then seems to have stopped snake backend from installing. Feel free to open an issue on github where it is easier to track and debug. I will make sure to update the install script to stop when it hits an error."

**Comment by alexkornitzer** [comment]
Awesome, so does the script run successfully if you install gcc then re-run it?

`sudo apt-get install gcc`

After the install you can run the below to check the status of the snake services:

```
systemctl status snake
sustemctl status snake-pit
```

**Comment by alexkornitzer** [comment]
I have updated the scripts to exit on first error, this should help prevent these errors being overlooked.
